services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: schmitz2301
      POSTGRES_DB: gymdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./pgadmin.env

    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db


  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: